spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret:
    key: "bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMjAyNCFAIyQlXiYqKCk="
  expiration: 86400000